name: Run ESLint for frontend
on:
  push:
    paths:
      - 'web/frontend'
  pull_request:
    paths:
      - 'web/frontedn'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm install
      - name: Run ESLint
        run: eslint
