name: Lint and format check

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
    - name: Setup go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
        go-version-file: './pkg/infra/go.mod'

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Installing golangci-lint
      run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

    - name: Formatting and linting the project
      run: make check